name: Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm config set //npm.pkg.github.com/:_authToken $TOKEN
        npm install
        npm run build
        npm publish
      env:
        TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Publish to npm
      uses: pascalgn/npm-publish-action@1.3.8
      env:
        TOKEN: ${{secrets.GITHUB_TOKEN}}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 